_BASE_: "R_50_FPN_1x_supervised.yaml"
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  WEIGHTS: "See Instructions"
  RESNETS:
    STRIDE_IN_1X1: False
INPUT:
  FORMAT: "RGB"
SOLVER:
  STEPS: (120000, 160000)
  MAX_ITER: 180000
